from .base import BaseEnum


class BlogTagType(BaseEnum):
    TECHNOLOGY = "TECHNOLOGY"
    DATA_SCIENCE = "DATA SCIENCE"
    AI_ML = "AI / ML"
    WEB_DEVELOPMENT = "WEB DEVELOPMENT"
    MOBILE_DEVELOPMENT = "MOBILE DEVELOPMENT"
    CLOUD_COMPUTING = "CLOUD COMPUTING"
    DEVOPS = "DEVOPS"
    CYBER_SECURITY = "CYBER SECURITY"
    DATABASES = "DATABASES"
    SOFTWARE_ENGINEERING = "SOFTWARE ENGINEERING"
    PROJECT_MANAGEMENT = "PROJECT MANAGEMENT"
    STARTUPS = "STARTUPS"
    ENTREPRENEURSHIP = "ENTREPRENEURSHIP"
    EVENTS = "EVENT", "EVENTS"
